module.exports = {
  TRANS_SELECT: "transselect",
  TRANS_UPDATE_GUPPY: "transupdateguppy",
  TRANS_UPDATE_BEELZEBUB: "transupdatebeelzebub",
  TRANS_UPDATE_FUN_GUY: "transupdatefunguy",
  TRANS_UPDATE_SERAPHIM: "transupdateseraphim",
  TRANS_UPDATE_BOB: "transupdatebob",
  TRANS_UPDATE_SPUN: "transupdatespun",
  TRANS_UPDATE_MOM: "transupdatemom",
  TRANS_UPDATE_CONJOINED: "transupdateconjoined",
  TRANS_UPDATE_LEVIATHAN: "transupdateleviathan",
  TRANS_UPDATE_OH_CRAP: "transupdateohcrap",
  TRANS_UPDATE_SUPER_BUM: "transupdatesuperbum",
  TRANS_UPDATE_BOOKWORM: "transupdatebookworm",
  TRANS_UPDATE_ADULTHOOD: "transupdateadulthood",
  TRANS_UPDATE_SPIDER_BABY: "transupdatespiderbaby",
  TRANS_UPDATE_STOMPY: "transupdatestompy",
  itemBasedTransformations: [
    "guppy",
    "beelzebub",
    "funguy",
    "seraphim",
    "bob",
    "spun",
    "mom",
    "conjoined",
    "leviathan",
    "ohcrap",
    "superbum",
    "bookworm",
    "spiderbaby"
  ],
  labels: {
    guppy: "Guppy",
    beelzebub: "Beelzebub",
    funguy: "Fun Guy",
    seraphim: "Seraphim",
    bob: "Bob",
    spun: "Spun",
    mom: "Mom",
    conjoined: "Conjoined",
    leviathan: "Leviathan",
    ohcrap: "Oh Crap",
    superbum: "Super Bum",
    bookworm: "Bookworm",
    adulthood: "Adulthood",
    spiderbaby: "Spider Baby",
    stompy: "Stompy"
  },
  order: [
    "guppy",
    "beelzebub",
    "funguy",
    "seraphim",
    "bob",
    "spun",
    "mom",
    "conjoined",
    "leviathan",
    "ohcrap",
    "superbum",
    "bookworm",
    "adulthood",
    "spiderbaby",
    "stompy"
  ]
};
